Repository woohaengshi/backend, pull requests merged in 2024-10, with the labels that each got.

#129 [FEAT] 회고 추가 및 회고와 공부한 과목을 수정하는 기능 추가
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/EditSubjectAndCommentRequest.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/SaveCommentRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/log/StatisticsLog.java
  src/main/java/com/woohaengshi/backend/repository/StudySubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
Labels: ✨ feature

#133 [FEAT] 이미지를 변경하는 기능 추가
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/SaveCommentRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/s3/AmazonS3Manager.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
Labels: ✨ feature

#132 [FEAT] 회원 정보를 수정하는 기능 추가
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/request/member/EditMemberInfoRequest.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/SaveCommentRequest.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/service/MemberServiceTest.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
Labels: ✨ feature

#135 [CI]: redis 설정 파일삭제
  .ebextensions-dev/03-redis.config
Labels: 🚨 hotfix

#136 [CI] redis 설정
  .ebextensions-dev/03-redis.config
Labels: 👷ci
