Repository woohaengshi/backend, pull requests merged in 2024-08, with the labels that each got.

#3 [FEAT] 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/woohaengshi/backend/BackendApplication.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/ErrorResponse.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/exception/WoohaengshiException.java
  src/test/java/com/woohaengshi/backend/BackendApplicationTests.java
Labels: ✨ feature

#6 [ ci] code format check workflow 추가
  .github/workflows/format-check.yml
  src/main/java/com/woohaengshi/backend/BackendApplication.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/exception/WoohaengshiException.java
  src/test/java/com/woohaengshi/backend/BackendApplicationTests.java
Labels: 👷ci

#10 [FEAT] 도메인 추가
  src/main/java/com/woohaengshi/backend/BackendApplication.java
  src/main/java/com/woohaengshi/backend/domain/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/StudyRecord.java
  src/main/java/com/woohaengshi/backend/domain/Subject.java
  src/main/java/com/woohaengshi/backend/domain/badge/Badge.java
  src/main/java/com/woohaengshi/backend/domain/badge/Name.java
  src/main/java/com/woohaengshi/backend/domain/member/Group.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/domain/member/State.java
Labels: ✨ feature

#11 [FEAT] 공부 기록 저장 기능
  .github/workflows/format-check.yml
  build.gradle
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/domain/StudyRecord.java
  src/main/java/com/woohaengshi/backend/domain/Subject.java
  src/main/java/com/woohaengshi/backend/domain/member/Course.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/SaveRecordRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/ErrorResponse.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/exception/ValidErrorResponse.java
  src/main/java/com/woohaengshi/backend/repository/MemberRepository.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/StudyRecordService.java
  src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/support/RepositoryTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
  src/test/java/com/woohaengshi/backend/support/fixture/StudyRecordFixture.java
Labels: ✨ feature

#16 [feat/#15]: Swagger 세팅
  build.gradle
  src/main/java/com/woohaengshi/backend/config/SwaggerConfig.java
Labels: ✨ feature

#17 [DB] 데이터베이스 형상 관리
  build.gradle
  src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#26 [FEAT] 학습 과목 테이블 추가에 따른 변경
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/domain/StudySubject.java
  src/main/java/com/woohaengshi/backend/dto/request/studyrecord/SaveRecordRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/StudySubjectRepository.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/StudyRecordServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceImplTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/StudyRecordFixture.java
Labels: ✨ feature

#24 [FEAT] 랭킹 조회 기능 추가
  src/main/java/com/woohaengshi/backend/controller/StatisticsController.java
  src/main/java/com/woohaengshi/backend/domain/statistics/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/statistics/StatisticsType.java
  src/main/java/com/woohaengshi/backend/dto/response/statistics/RankDataResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/statistics/RanksResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/statistics/ShowRankSnapshotResponse.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsService.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/StatisticsControllerTest.java
  src/test/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImplTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
  src/test/java/com/woohaengshi/backend/support/fixture/StatisticsFixture.java
Labels: ✨ feature

#47 [FEAT] 캘린더 월 별 공부 기록 조회 기능 추가
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/controller/TimerController.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowDailyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerService.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/StatisticsControllerTest.java
  src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
Labels: ✨ feature

#49 [CI] 무중단 CI/CD 배포
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .ebextensions-dev/02-https-redirect.config
  .github/workflows/dev_deploy.yml
  .github/workflows/format-check.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/woohaengshi/backend/controller/RootController.java
  src/main/resources/application-dev.yml
Labels: 👷ci

#25 [FEAT] 과목 편집 기능 추가
  src/main/java/com/woohaengshi/backend/controller/SubjectController.java
  src/main/java/com/woohaengshi/backend/dto/request/subject/SubjectRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectService.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/SubjectControllerTest.java
  src/test/java/com/woohaengshi/backend/service/SubjectServiceImplTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/SubjectFixture.java
Labels: ✨ feature

#50 [FEAT] 캘린더 연 조회
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyTotalResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowYearlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/result/MonthlyTotalRecordResult.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/StudyRecordControllerTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
Labels: ✨ feature

#56 [HOTFIX] study record controller 에서 오타 수정
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
Labels: 🚨 hotfix

#53 [FEAT] 회원 가입 기능 추가
  build.gradle
  src/main/java/com/woohaengshi/backend/config/AuthConfig.java
  src/main/java/com/woohaengshi/backend/controller/auth/AuthController.java
  src/main/java/com/woohaengshi/backend/domain/StudySubject.java
  src/main/java/com/woohaengshi/backend/domain/statistics/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/subject/DefaultSubject.java
  src/main/java/com/woohaengshi/backend/domain/subject/Subject.java
  src/main/java/com/woohaengshi/backend/dto/request/auth/SignInRequest.java
  src/main/java/com/woohaengshi/backend/dto/request/auth/SignUpRequest.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/subject/ShowSubjectsResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/repository/MemberRepository.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthService.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/SubjectFixture.java
Labels: ✨ feature

#61 [FEAT] 회원 가입시 Course를 string으로 받도록 변경
  src/main/java/com/woohaengshi/backend/domain/member/Course.java
  src/main/java/com/woohaengshi/backend/dto/request/auth/SignInRequest.java
  src/main/java/com/woohaengshi/backend/dto/request/auth/SignUpRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/ErrorResponse.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
Labels: ✨ feature

#54 [FEAT] DailyTime 빼고 StudyRecord에서 계산해서 반영
  src/main/java/com/woohaengshi/backend/BackendApplication.java
  src/main/java/com/woohaengshi/backend/controller/SubjectController.java
  src/main/java/com/woohaengshi/backend/domain/statistics/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/statistics/StatisticsType.java
  src/main/java/com/woohaengshi/backend/dto/response/statistics/RankDataResponse.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/woohaengshi/backend/controller/StatisticsControllerTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/StatisticsFixture.java
Labels: ♻️ refactor

#66 [CI]: 배포용 application 코드 수정
  src/main/resources/application-dev.yml
Labels: 👷ci

#69 [CI] 배포
  src/main/java/com/woohaengshi/backend/config/AuthConfig.java
  src/main/java/com/woohaengshi/backend/controller/RootController.java
Labels: 👷ci

#70 [REFACTOR]: Statistics 코드 리팩토링
  src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsSpecification.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordSpecification.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
Labels: ♻️ refactor

#82 [FEAT] S3 이미지 설정
  build.gradle
  src/main/java/com/woohaengshi/backend/config/S3Config.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/s3/AmazonS3Manager.java
  src/main/java/com/woohaengshi/backend/s3/Filepath.java
Labels: ✨ feature

#78 [FEAT] 실시간 집계 업데이트 및 공부 기록, 회원 가입 기능 수정
  src/main/java/com/woohaengshi/backend/domain/StudyRecord.java
  src/main/java/com/woohaengshi/backend/domain/statistics/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/subject/DefaultSubject.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/repository/MemberRepository.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/test/java/com/woohaengshi/backend/repository/StatisticsRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/StatisticsFixture.java
Labels: ✨ feature

#76 [FEAT] 캘린더 월 조회 api 수정
  src/main/java/com/woohaengshi/backend/domain/StudyRecord.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/subject/ShowSubjectsResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/dto/result/DailyStudyRecordResult.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
Labels: ✨ feature

#85 [CI]: yml s3 설정 추가
  src/main/resources/application-dev.yml
Labels: 👷ci

#86 [CI] 배포
  build.gradle
  src/main/java/com/woohaengshi/backend/config/S3Config.java
  src/main/java/com/woohaengshi/backend/domain/StudyRecord.java
  src/main/java/com/woohaengshi/backend/domain/statistics/Statistics.java
  src/main/java/com/woohaengshi/backend/domain/subject/DefaultSubject.java
  src/main/java/com/woohaengshi/backend/dto/request/subject/SubjectRequest.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/subject/ShowSubjectsResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/dto/result/DailyStudyRecordResult.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/woohaengshi/backend/repository/MemberRepository.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsSpecification.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordSpecification.java
  src/main/java/com/woohaengshi/backend/s3/AmazonS3Manager.java
  src/main/java/com/woohaengshi/backend/s3/Filepath.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectServiceImpl.java
  src/main/resources/application-dev.yml
  src/test/java/com/woohaengshi/backend/repository/StatisticsRepositoryTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/SubjectServiceTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/StatisticsFixture.java
Labels: 👷ci

#88 [FEAT] 캘린더 조회 QueryDsl 사용하도록 변경
  build.gradle
  src/main/java/com/woohaengshi/backend/config/QueryDslConfig.java
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowDailyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/subject/ShowSubjectsResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/dto/result/ShowCalendarResult.java
  src/main/java/com/woohaengshi/backend/dto/result/SubjectResult.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepository.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepositoryImpl.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
  src/test/java/com/woohaengshi/backend/support/RepositoryTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/SubjectFixture.java
Labels: ♻️ refactor, ✨ feature

#84 [FEAT] 회원 정보 조회 기능 추가
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/service/MemberServiceTest.java
Labels: ✨ feature

#90 [FEAT] 비밀번호 변경 기능
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/request/member/ChangePasswordRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
Labels: ✨ feature

#91 [CI] 배포
  build.gradle
  src/main/java/com/woohaengshi/backend/config/QueryDslConfig.java
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/controller/StudyRecordController.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/request/member/ChangePasswordRequest.java
  src/main/java/com/woohaengshi/backend/dto/response/member/ShowMemberResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowDailyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/studyrecord/ShowMonthlyRecordResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/subject/ShowSubjectsResponse.java
  src/main/java/com/woohaengshi/backend/dto/response/timer/ShowTimerResponse.java
  src/main/java/com/woohaengshi/backend/dto/result/ShowCalendarResult.java
  src/main/java/com/woohaengshi/backend/dto/result/SubjectResult.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepository.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepositoryImpl.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordService.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/MemberServiceTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
  src/test/java/com/woohaengshi/backend/support/RepositoryTest.java
  src/test/java/com/woohaengshi/backend/support/fixture/MemberFixture.java
  src/test/java/com/woohaengshi/backend/support/fixture/SubjectFixture.java
Labels: 👷ci

#94 [FEAT] 회원 탈퇴 기능
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/controller/auth/AuthController.java
  src/main/java/com/woohaengshi/backend/controller/auth/CookieProvider.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/result/SignInResult.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthService.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
Labels: ✨ feature

#96 [FEAT] 프론트엔드 배포 주소 추가
  src/main/java/com/woohaengshi/backend/config/WebConfig.java
  src/main/java/com/woohaengshi/backend/controller/RootController.java
Labels: ✨ feature

#97 [CI] 배포하기
  src/main/java/com/woohaengshi/backend/config/WebConfig.java
  src/main/java/com/woohaengshi/backend/controller/MemberController.java
  src/main/java/com/woohaengshi/backend/controller/RootController.java
  src/main/java/com/woohaengshi/backend/controller/auth/AuthController.java
  src/main/java/com/woohaengshi/backend/controller/auth/CookieProvider.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/dto/result/SignInResult.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthService.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberService.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/MemberControllerTest.java
  src/test/java/com/woohaengshi/backend/controller/auth/AuthControllerTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/service/member/MemberServiceTest.java
Labels: 👷ci

#99 [fix]: 랭킹 주간 버그 수정
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
Labels: 🐞bug, 🚨 hotfix

#100 [fix]: 엑세스 토큰 시간 증가
  src/main/resources/application-dev.yml
Labels: 👷ci

#102 [!HOTFIX] 과목 수정시 STATE 값으로 관리하도록 변경
  src/main/java/com/woohaengshi/backend/domain/subject/Subject.java
  src/main/java/com/woohaengshi/backend/dto/request/subject/SubjectRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/woohaengshi/backend/service/SubjectServiceTest.java
Labels: 🚨 hotfix

#103 [CI] 배포하기
  src/main/java/com/woohaengshi/backend/controller/RootController.java
  src/main/java/com/woohaengshi/backend/domain/subject/Subject.java
  src/main/java/com/woohaengshi/backend/dto/request/subject/SubjectRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/subject/SubjectServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/woohaengshi/backend/service/SubjectServiceTest.java
Labels: 👷ci

#105 [HOTFIX] 과목 조회 시 활성화된 과목만 조회하도록 수정
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
Labels: 🚨 hotfix

#106 [CI] 배포하기
  src/main/java/com/woohaengshi/backend/repository/SubjectRepository.java
  src/main/java/com/woohaengshi/backend/service/timer/TimerServiceImpl.java
  src/test/java/com/woohaengshi/backend/service/TimerServiceTest.java
Labels: 👷ci

#107 [FIX] 시간 버그 로직 추가
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
Labels: 🐞bug, 🚨 hotfix

#108 [CI] 배포
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
Labels: 👷ci
