Repository woohaengshi/backend, pull requests merged in 2024-09, with the labels that each got.

#109 [FEAT] 회원 탈퇴 검증 기능 추가
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
Labels: ✨ feature

#112 [FIX] scheduler 에러 수정
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
Labels: 🚨 hotfix

#113 [FEAT] 누락된 커밋 추가
  src/main/java/com/woohaengshi/backend/config/WebConfig.java
Labels: ✨ feature

#114 [CI] 배포
  src/main/java/com/woohaengshi/backend/config/WebConfig.java
  src/main/java/com/woohaengshi/backend/domain/member/Member.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/member/MemberServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
Labels: 👷ci

#110 [REFACTOR] 랭킹 조회 리팩토링
  src/main/java/com/woohaengshi/backend/dto/response/statistics/ShowRankSnapshotResponse.java
  src/main/java/com/woohaengshi/backend/repository/StatisticsSpecification.java
  src/main/java/com/woohaengshi/backend/repository/StudyRecordSpecification.java
  src/main/java/com/woohaengshi/backend/repository/statistics/StatisticsCustomRepository.java
  src/main/java/com/woohaengshi/backend/repository/statistics/StatisticsCustomRepositoryImpl.java
  src/main/java/com/woohaengshi/backend/repository/statistics/StatisticsRepository.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepository.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordCustomRepositoryImpl.java
  src/main/java/com/woohaengshi/backend/repository/studyrecord/StudyRecordRepository.java
  src/main/java/com/woohaengshi/backend/service/auth/AuthServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsScheduler.java
  src/main/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImpl.java
  src/main/java/com/woohaengshi/backend/service/studyrecord/StudyRecordServiceImpl.java
  src/test/java/com/woohaengshi/backend/repository/StatisticsRepositoryTest.java
  src/test/java/com/woohaengshi/backend/repository/StudyRecordRepositoryTest.java
  src/test/java/com/woohaengshi/backend/service/StudyRecordServiceTest.java
  src/test/java/com/woohaengshi/backend/service/auth/AuthServiceTest.java
  src/test/java/com/woohaengshi/backend/service/statistics/StatisticsServiceImplTest.java
Labels: ♻️ refactor

#121 [FEAT] 이메일 인증을 통한 비밀번호 재설정 기능
  build.gradle
  src/main/java/com/woohaengshi/backend/config/AuthConfig.java
  src/main/java/com/woohaengshi/backend/controller/PasswordController.java
  src/main/java/com/woohaengshi/backend/controller/auth/AuthInterceptor.java
  src/main/java/com/woohaengshi/backend/dto/request/password/ChangePasswordRequest.java
  src/main/java/com/woohaengshi/backend/dto/request/password/SendMailRequest.java
  src/main/java/com/woohaengshi/backend/exception/ErrorCode.java
  src/main/java/com/woohaengshi/backend/exception/ValidErrorResponse.java
  src/main/java/com/woohaengshi/backend/repository/AuthenticationCode.java
  src/main/java/com/woohaengshi/backend/repository/AuthenticationCodeRepository.java
  src/main/java/com/woohaengshi/backend/service/password/PasswordService.java
  src/main/java/com/woohaengshi/backend/service/password/PasswordServiceImpl.java
  src/test/java/com/woohaengshi/backend/controller/PasswordControllerTest.java
Labels: ✨ feature
